### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by Elkropac**
I have taken error codes from czech manual pdf

### CODE REVIEW

**Comment by Elkropac** [comment]
Seems i'm missing one translation, please don't merge

**Comment by Elkropac** [comment]
Fixed

**Comment by mathieu-mp** [comment]
Hi @Elkropac, thank you for your contribution !!!

We have a validate error: Invalid JSON file translations/sensor.cs.json

**Comment by mathieu-mp** [comment]
A coma is missing on translations/sensor.cs.json:24

**Comment by mathieu-mp** [comment]
I had a look at other czech translation files ([this one for example](https://github.com/home-assistant/core/blob/4a50010458e3552cba4e617eb827839587a9be79/homeassistant/components/eight_sleep/translations/cs.json)), and they use unicode accentuated characters. I don't know if it is mandatory.

**Comment by Elkropac** [comment]
> A coma is missing on translations/sensor.cs.json:24

sorry about that

**Comment by Elkropac** [comment]
> I had a look at other czech translation files ([this one for example](https://github.com/home-assistant/core/blob/4a50010458e3552cba4e617eb827839587a9be79/homeassistant/components/eight_sleep/translations/cs.json)), and they use unicode accentuated characters. I don't know if it is mandatory.

Yep, i saw it too. I don't know, if it's needed. I tested my strings and it seems to be ok. It's UTF-8, so what could be wrong. When you check other Frech translations, it's also writen i unicode characters

**Review by mathieu-mp — APPROVED** [review]
I can't say my czech is fluent enough to reread your translations, but the code syntax is nice !
Thanks !

**Comment by Elkropac** [comment]
Thanks ;) I have taken most of it from czech pdf, some parts translated myself and checked with deepl.com

**Pull request merged**
