### PR TITLE
Refactor setup to solve deprecation from 2023.5

### LINKED ISSUE #47: Cannot connect to Spa from Home Assistant ⩾ 2023.5.0
With the latest update of home assistant (2023.5.0), i lost the connection with my spa.
This is the log entry:

```
Logger: homeassistant.config_entries
Source: custom_components/intex_spa/__init__.py:48
Integration: Intex Spa ([documentation](https://github.com/mathieu-mp/homeassistant-intex-spa), [issues](https://github.com/mathieu-mp/homeassistant-intex-spa/issues))
First occurred: 12:42:01 (1 occurrences)
Last logged: 12:42:01

Error setting up entry Spa for intex_spa
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/intex_spa/__init__.py", line 48, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

```

### PR DESCRIPTION
**Pull request by FredericMa**
I encountered the same issue as described in #47.
I googled a bit and came across a similar fix of another component: https://github.com/zachcheatham/ha-omada/commit/4d9d9c2b459caa78c4a7c9ce5e0402b1026a5112

I changed it on my system and all is back up and running.

Fixes #47

### CODE REVIEW

**Comment by johanveld** [comment]
Tested the changes and can confirm it works now.

**Comment by mathieu-mp** [comment]
Big thanks for your work on this Pull Request !
I will check why the tests don't pass, fix and publish.

**Comment by FredericMa** [comment]
Right, I didn't think about the tests, sorry.
I just tried to figure out what is wrong but I'm not familiar enough with python testing.

**Review by mathieu-mp — APPROVED** [review]
Code works fine, only tests won't pass.
Tests failures do not look linked to this specific code, shall be solved in another issue.

**Pull request merged**
