### PR TITLE
Use uid as device entity identifier

### PR DESCRIPTION
**Pull request by mathieu-mp**
**Breaking change:** devices have to be deleted then re-added

### CODE REVIEW

**Comment by Elkropac** [comment]
Hi, are we sure, that uid is really unique per device? I think we have not seen two uids from the same model yet.
What if same model has same uid? Then you cannot have more spa's of same model in HA.

I used IP with uid as unique id, but HA documentation says not to use IP address in unique id 
```
    unique_id = info['ip'] + ' ' + info['uid']
    unique_id = hashlib.md5(unique_id.encode())
    data['info'] = info
    data['info']['unique_id'] = unique_id.hexdigest()
```
https://github.com/Elkropac/hassio-intex-spa/blob/c7c89e2428b398bed54bc1cb2957edb021ee7010/custom_components/intex_spa/config_flow.py#L54

**Comment by mathieu-mp** [comment]
> Hi, are we sure, that uid is really unique per device? I think we have not seen two uids from the same model yet. What if same model has same uid? Then you cannot have more spa's of same model in HA.

I agree, and I just assume uid means _unique id_. I'd like to find two people with the same spa model to validate this hypothesis.

> 
> I used IP with uid as unique id, but HA documentation says not to use IP address in unique id
> 
> ```
>     unique_id = info['ip'] + ' ' + info['uid']
>     unique_id = hashlib.md5(unique_id.encode())
>     data['info'] = info
>     data['info']['unique_id'] = unique_id.hexdigest()
> ```
> 
> https://github.com/Elkropac/hassio-intex-spa/blob/c7c89e2428b398bed54bc1cb2957edb021ee7010/custom_components/intex_spa/config_flow.py#L54

Yeah, I read this recommandation from HA doc. That's why I wanted to avoid the current use of the spa name as the unique identifier. I am not so much into using another "forbidden" parameter to replace a previous "forbidden" parameter.
I'll just stay on the above assumption for now, and fix it if eventually.

**Comment by Elkropac** [comment]
> > Hi, are we sure, that uid is really unique per device? I think we have not seen two uids from the same model yet. What if same model has same uid? Then you cannot have more spa's of same model in HA.
> 
> I agree, and I just assume uid means _unique id_. I'd like to find two people with the same spa model to validate this hypothesis.
> 
I think it is ok for now. I guess there are not many people with more than one spa of the same model at home.
Hope we can collect more data from people.

> > I used IP with uid as unique id, but HA documentation says not to use IP address in unique id
> 
> Yeah, I read this recommandation from HA doc. That's why I wanted to avoid the current use of the spa name as the unique identifier. I am not so much into using another "forbidden" parameter to replace a previous "forbidden" parameter. I'll just stay on the above assumption for now, and fix it if eventually.

Strictly speaking, I have not used IP adress as unique id in my code. It's just a hash of IP and UID together.

**Comment by mathieu-mp** [comment]
> I think it is ok for now. (...) Hope we can collect more data from people.

Thank you very much for your contributions ! 🥇

**Comment by mathieu-mp** [comment]
Implemented by #24

**Pull request closed without merging**
